/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffebrew;

/**
 *
 * @author x17333376
 */
public class CoffeBrewGui extends javax.swing.JFrame {
   final private double drinks[],snacks[],costs[];
   final private double latte,capi,frappe,flatWhite,hotChoco,cookie,croissant,sandwich,cake,crisp;
   
    /**
     * Creates new form CoffeBrewGui
     */
    public CoffeBrewGui() {
        initComponents();
        drinks=new double [5];
        snacks=new double [5];
        costs= new double [3];
        latte=3.00;
        capi=1.20;
        frappe=3.00;
        flatWhite=2.50;
        hotChoco=2.50;
        cookie=1.00;
        croissant=2.60;
        sandwich=1.80;
        cake=2.00;
        crisp=3.00;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCheckLatte = new javax.swing.JCheckBox();
        jCheckFrappe = new javax.swing.JCheckBox();
        jCheckCapuccino = new javax.swing.JCheckBox();
        jCheckHotChocolate = new javax.swing.JCheckBox();
        jCheckFlatWhite = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LatteSpinner = new javax.swing.JSpinner();
        FrappeSpinner = new javax.swing.JSpinner();
        CapuccinoSpinner = new javax.swing.JSpinner();
        HotChocolateSpinner = new javax.swing.JSpinner();
        FlatWhiteSpinner = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextReceipt = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jCheckCroissant = new javax.swing.JCheckBox();
        jCheckCookie = new javax.swing.JCheckBox();
        jCheckSandwich = new javax.swing.JCheckBox();
        jCheckCrisps = new javax.swing.JCheckBox();
        jCheckCake = new javax.swing.JCheckBox();
        CroissantSpinner = new javax.swing.JSpinner();
        CookieSpinner = new javax.swing.JSpinner();
        SandwichSpinner = new javax.swing.JSpinner();
        CrispSpinner = new javax.swing.JSpinner();
        CakeSpinner = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        Tip = new javax.swing.JLabel();
        SubTotal = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jTextSubTotal = new javax.swing.JTextField();
        jTextTip = new javax.swing.JTextField();
        jTextTotal = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        TotalBtn = new javax.swing.JButton();
        jButtonReceipt = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        TotalDrinks = new javax.swing.JLabel();
        TotalSnacks = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextTotalDrinks = new javax.swing.JTextField();
        jTextTotalSnacks = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 70)); // NOI18N
        jLabel1.setText("CoffeeBrew");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jCheckLatte.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jCheckLatte.setText("Latte");
        jCheckLatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckLatteActionPerformed(evt);
            }
        });

        jCheckFrappe.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jCheckFrappe.setText("Frappe");

        jCheckCapuccino.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jCheckCapuccino.setText("Capuccino");
        jCheckCapuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckCapuccinoActionPerformed(evt);
            }
        });

        jCheckHotChocolate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jCheckHotChocolate.setText("Hot Chocolate");

        jCheckFlatWhite.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jCheckFlatWhite.setText("Flat White");

        LatteSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        LatteSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                LatteSpinnerStateChanged(evt);
            }
        });

        FrappeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        FrappeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FrappeSpinnerStateChanged(evt);
            }
        });

        CapuccinoSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        CapuccinoSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CapuccinoSpinnerStateChanged(evt);
            }
        });

        HotChocolateSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        HotChocolateSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                HotChocolateSpinnerStateChanged(evt);
            }
        });

        FlatWhiteSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        FlatWhiteSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FlatWhiteSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jCheckLatte, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckFlatWhite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckHotChocolate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckCapuccino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckFrappe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FrappeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LatteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CapuccinoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HotChocolateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FlatWhiteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckLatte)
                    .addComponent(LatteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckFrappe)
                    .addComponent(FrappeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckCapuccino)
                    .addComponent(CapuccinoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckHotChocolate)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addComponent(HotChocolateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckFlatWhite)
                    .addComponent(FlatWhiteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextReceipt.setColumns(20);
        jTextReceipt.setRows(5);
        jScrollPane1.setViewportView(jTextReceipt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jCheckCroissant.setText("Croissant");

        jCheckCookie.setText("Cookie");

        jCheckSandwich.setText("Sandwich");

        jCheckCrisps.setText("Crisps");

        jCheckCake.setText("Cake");

        CroissantSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        CroissantSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CroissantSpinnerStateChanged(evt);
            }
        });

        CookieSpinner.setModel(new javax.swing.SpinnerNumberModel());
        CookieSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CookieSpinnerStateChanged(evt);
            }
        });

        SandwichSpinner.setModel(new javax.swing.SpinnerNumberModel());
        SandwichSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SandwichSpinnerStateChanged(evt);
            }
        });

        CrispSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        CrispSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CrispSpinnerStateChanged(evt);
            }
        });

        CakeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        CakeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CakeSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckCookie)
                        .addComponent(jCheckCroissant))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckSandwich)
                        .addComponent(jCheckCrisps)
                        .addComponent(jCheckCake)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(CakeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CroissantSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CrispSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(CookieSpinner, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(SandwichSpinner, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckCroissant)
                    .addComponent(CroissantSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckCookie)
                    .addComponent(CookieSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckSandwich)
                    .addComponent(SandwichSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckCrisps)
                    .addComponent(CrispSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckCake)
                    .addComponent(CakeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Tip.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Tip.setText("Tip");

        SubTotal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        SubTotal.setText("Sub Total");

        Total.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Total.setText("Total");

        jTextSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextSubTotal.setText("0");

        jTextTip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTip.setText("0");

        jTextTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTotal.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SubTotal)
                    .addComponent(Tip, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextSubTotal)
                    .addComponent(jTextTip)
                    .addComponent(jTextTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubTotal)
                    .addComponent(jTextSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tip)
                    .addComponent(jTextTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total)
                    .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TotalBtn.setText("Total");
        TotalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalBtnActionPerformed(evt);
            }
        });

        jButtonReceipt.setText("Receipt");
        jButtonReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceiptActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonReceipt)
                    .addComponent(TotalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonReset)
                    .addComponent(jButtonClose))
                .addGap(62, 62, 62))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalBtn)
                    .addComponent(jButtonReset))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReceipt)
                    .addComponent(jButtonClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        TotalDrinks.setText("Total Drinks");

        TotalSnacks.setText("Total Snacks");

        jTextTotalDrinks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTotalDrinks.setText("0");

        jTextTotalSnacks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTotalSnacks.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(TotalDrinks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextTotalDrinks))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(TotalSnacks))
                        .addGap(10, 10, 10)
                        .addComponent(jTextTotalSnacks, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalDrinks)
                    .addComponent(jTextTotalDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTotalSnacks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalSnacks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(390, 390, 390)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(610, 610, 610)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(140, 140, 140)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(380, 380, 380)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckLatteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckLatteActionPerformed

    private void jCheckCapuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckCapuccinoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jCheckCapuccinoActionPerformed

    private void LatteSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_LatteSpinnerStateChanged
        // TODO add your handling code here:
        int a=(Integer)LatteSpinner.getValue();
        drinks[0]=a*latte;
        jTextTotalDrinks.setText("€ "+(drinks[0]+drinks[1]+drinks[2]+drinks[3]+drinks[4]));
    }//GEN-LAST:event_LatteSpinnerStateChanged

    private void FrappeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FrappeSpinnerStateChanged
        // TODO add your handling code here:
        int a=(Integer)FrappeSpinner.getValue();
        drinks[1]=a*frappe;
        jTextTotalDrinks.setText("€ "+(drinks[0]+drinks[1]+drinks[2]+drinks[3]+drinks[4]));
    }//GEN-LAST:event_FrappeSpinnerStateChanged

    private void CapuccinoSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CapuccinoSpinnerStateChanged
        int a=(Integer)CapuccinoSpinner.getValue();
        drinks[2]=a*capi;
        jTextTotalDrinks.setText("€ "+(drinks[0]+drinks[1]+drinks[2]+drinks[3]+drinks[4]));
    }//GEN-LAST:event_CapuccinoSpinnerStateChanged

    private void HotChocolateSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_HotChocolateSpinnerStateChanged
        int a=(Integer)HotChocolateSpinner.getValue();
        drinks[3]=a*hotChoco;
        jTextTotalDrinks.setText("€ "+(drinks[0]+drinks[1]+drinks[2]+drinks[3]+drinks[4]));
    }//GEN-LAST:event_HotChocolateSpinnerStateChanged

    private void FlatWhiteSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FlatWhiteSpinnerStateChanged
        // TODO add your handling code here:
        int a=(Integer)FlatWhiteSpinner.getValue();
        drinks[4]=a*flatWhite;
        jTextTotalDrinks.setText("€ "+(drinks[0]+drinks[1]+drinks[2]+drinks[3]+drinks[4]));
    }//GEN-LAST:event_FlatWhiteSpinnerStateChanged

    private void CroissantSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CroissantSpinnerStateChanged
        // TODO add your handling code here:
        int a=(Integer)CroissantSpinner.getValue();
        snacks[0]=a*croissant;
        jTextTotalSnacks.setText("€ "+(snacks[0]+snacks[1]+snacks[2]+snacks[3]+snacks[4]));
    }//GEN-LAST:event_CroissantSpinnerStateChanged

    private void CookieSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CookieSpinnerStateChanged
        // TODO add your handling code here:
        int a=(Integer)CookieSpinner.getValue();
        snacks[1]=a*cookie;
        jTextTotalSnacks.setText("€ "+(snacks[0]+snacks[1]+snacks[2]+snacks[3]+snacks[4]));
    }//GEN-LAST:event_CookieSpinnerStateChanged

    private void SandwichSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SandwichSpinnerStateChanged
        // TODO add your handling code here:
        int a=(Integer)SandwichSpinner.getValue();
        snacks[2]=a*sandwich;
        jTextTotalSnacks.setText("€ "+(snacks[0]+snacks[1]+snacks[2]+snacks[3]+snacks[4]));
    }//GEN-LAST:event_SandwichSpinnerStateChanged

    private void CrispSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CrispSpinnerStateChanged
        // TODO add your handling code here:
        int a=(Integer)CrispSpinner.getValue();
        snacks[3]=a*crisp;
        jTextTotalSnacks.setText("€ "+(snacks[0]+snacks[1]+snacks[2]+snacks[3]+snacks[4]));
    }//GEN-LAST:event_CrispSpinnerStateChanged

    private void CakeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CakeSpinnerStateChanged
        // TODO add your handling code here:
        int a=(Integer)CakeSpinner.getValue();
        snacks[4]=a*cake;
        jTextTotalSnacks.setText("€ "+(snacks[0]+snacks[1]+snacks[2]+snacks[3]+snacks[4]));
    }//GEN-LAST:event_CakeSpinnerStateChanged

    private void TotalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalBtnActionPerformed
        // TODO add your handling code here:
        jTextSubTotal.setText("€ "+(snacks[0]+snacks[1]+snacks[2]+snacks[3]+snacks[4]+drinks[0]+drinks[1]+drinks[2]+drinks[3]+drinks[4]));
        jTextTip.setText("€ "+(snacks[0]+snacks[1]+snacks[2]+snacks[3]+snacks[4]+drinks[0]+drinks[1]+drinks[2]+drinks[3]+drinks[4])*.1);
        jTextTotal.setText("€ "+ (snacks[0]+snacks[1]+snacks[2]+snacks[3]+snacks[4]+drinks[0]+drinks[1]+drinks[2]+drinks[3]+drinks[4]+(snacks[0]+snacks[1]+snacks[2]+snacks[3]+snacks[4]+drinks[0]+drinks[1]+drinks[2]+drinks[3]+drinks[4])*.1));
    }//GEN-LAST:event_TotalBtnActionPerformed

    private void jButtonReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceiptActionPerformed
        // TODO add your handling code here:
        drinks[0] = Double.parseDouble(LatteSpinner.getValue());
        drinks[1] = Double.parseDouble(FrappeSpinner.getText());
        drinks[2] = Double.parseDouble(CapuccinoSpinner.getText());
        drinks[3] = Double.parseDouble(HotChocolateSpinner.getText());
        drinks[4] = Double.parseDouble(FlatWhiteSpinner.getText());

        snacks[0] = Double.parseDouble(CroissantSpinner.getText());
        snacks[1] = Double.parseDouble(CookieSpinner.getText());
        snacks[2] = Double.parseDouble(SandwichSpinner.getText());
        snacks[3] = Double.parseDouble(CrispSpinner.getText());
        snacks[4] = Double.parseDouble(CakeSpinner.getText());

        costs[0] = Double.parseDouble(jTextSubTotal.getText());
        costs[1] = Double.parseDouble(jTextTip.getText());
        costs[2] = Double.parseDouble(jTextTotal.getText());

        jTextReceipt.append("CoffeeBrew Receipt" +
            "=======================================" +
            "\nLatte " + drinks[0] +
            "\nFrappe " + drinks[1] +
            "\nCappucino " + drinks[2] +
            "\nHotChocolate " + drinks[3] +
            "\nFlatWhite " + drinks[4] +
            "\n====================================" +
            "\nCrossaint " + snacks[0] +
            "\nCookie " + snacks[1] +
            "\nSandwich " + snacks[2] +
            "\nCrisps " + snacks[3] +
            "\nCake " + snacks[4] +
            "\n=====================================" +
            "\n Sub Total " + costs[0] +
            "\n Tip " + costs[1] +
            "\n Total " + costs[2] +
            "\n=========================================" +
            "\nThank Your For Shopping At CoffeeBrew");
    }//GEN-LAST:event_jButtonReceiptActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextTotalDrinks.setText("0");
        jTextTotalSnacks.setText("0");
        jTextSubTotal.setText("0");
        LatteSpinner.setValue(0);
        FrappeSpinner.setValue(0);
        CapuccinoSpinner.setValue(0);
        HotChocolateSpinner.setValue(0);
        FlatWhiteSpinner.setValue(0);
        CroissantSpinner.setValue(0);
        CookieSpinner.setValue(0);
        SandwichSpinner.setValue(0);
        CrispSpinner.setValue(0);
        CakeSpinner.setValue(0);
        jTextSubTotal.setText("0");
        jTextTip.setText("0");
        jTextTotal.setText("0");
        jTextReceipt.setText(null);
        jCheckLatte.setSelected(false);
        jCheckFrappe.setSelected(false);
        jCheckCapuccino.setSelected(false);
        jCheckHotChocolate.setSelected(false);
        jCheckFlatWhite.setSelected(false);
        jCheckCroissant.setSelected(false);
        jCheckCookie.setSelected(false);
        jCheckSandwich.setSelected(false);
        jCheckCrisps.setSelected(false);
        jCheckCake.setSelected(false);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeBrewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeBrewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeBrewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeBrewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeBrewGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner CakeSpinner;
    private javax.swing.JSpinner CapuccinoSpinner;
    private javax.swing.JSpinner CookieSpinner;
    private javax.swing.JSpinner CrispSpinner;
    private javax.swing.JSpinner CroissantSpinner;
    private javax.swing.JSpinner FlatWhiteSpinner;
    private javax.swing.JSpinner FrappeSpinner;
    private javax.swing.JSpinner HotChocolateSpinner;
    private javax.swing.JSpinner LatteSpinner;
    private javax.swing.JSpinner SandwichSpinner;
    private javax.swing.JLabel SubTotal;
    private javax.swing.JLabel Tip;
    private javax.swing.JLabel Total;
    private javax.swing.JButton TotalBtn;
    private javax.swing.JLabel TotalDrinks;
    private javax.swing.JLabel TotalSnacks;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonReceipt;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JCheckBox jCheckCake;
    private javax.swing.JCheckBox jCheckCapuccino;
    private javax.swing.JCheckBox jCheckCookie;
    private javax.swing.JCheckBox jCheckCrisps;
    private javax.swing.JCheckBox jCheckCroissant;
    private javax.swing.JCheckBox jCheckFlatWhite;
    private javax.swing.JCheckBox jCheckFrappe;
    private javax.swing.JCheckBox jCheckHotChocolate;
    private javax.swing.JCheckBox jCheckLatte;
    private javax.swing.JCheckBox jCheckSandwich;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextReceipt;
    private javax.swing.JTextField jTextSubTotal;
    private javax.swing.JTextField jTextTip;
    private javax.swing.JTextField jTextTotal;
    private javax.swing.JTextField jTextTotalDrinks;
    private javax.swing.JTextField jTextTotalSnacks;
    // End of variables declaration//GEN-END:variables
}
